name: MD-TO-HTML-ENCODER

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
	  
    - name: Installation
      run: |
	  yarn
	  export NODE_OPTIONS="--max_old_space_size=4096"
	  
    - name: Build
      run: yarn build

    - name: Deploy 
      uses: peaceiris/actions-gh-pages@v2
      env:
        #ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: './build/' 
        ##################################################   
    #- name: Moving images to gh-pages directory
     ## working-directory: master
      #run: chmod +x scripts/update-images.sh
   ################################################